/**
 * rules.test.ts
 * Tests for the account rules, the modes, the leagues and, above all, that
 * the database (supabase/schema.sql) accepts and does exactly what the
 * game expects.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { LEAGUE_POINTS, LEAGUES, leagueFor, leagueProgress } from "../src/config/leagues";
import { climbFactor, findMode, MAX_CLIMB, MODES, secondsForQuestion, VERSUS_MODE } from "../src/config/modes";
import { internalEmail, isValidUsername, normalizeUsername } from "../src/config/rules";

const sql = readFileSync("supabase/schema.sql", "utf8");

test("validates usernames", () => {
    assert.ok(isValidUsername("ana_92"));
    assert.ok(isValidUsername(normalizeUsername("  JonDals ")));
    assert.ok(!isValidUsername("ab"));
    assert.ok(!isValidUsername("with space"));
    assert.ok(!isValidUsername("ñandú"));
    assert.ok(!isValidUsername("a".repeat(21)));
    assert.equal(internalEmail("ana_92"), "ana_92@quizmania.app");
});

test("there are ten modes, all different, and Versus is separate", () => {
    assert.equal(MODES.length, 10);
    assert.equal(new Set(MODES.map((mode) => mode.id)).size, MODES.length);
    assert.ok(!MODES.includes(VERSUS_MODE));
    assert.equal(findMode("versus"), VERSUS_MODE);
    assert.equal(findMode("a-mode-that-no-longer-exists"), MODES[0]);
    for (const mode of MODES) assert.ok(mode.short.es.length <= 9 && mode.short.en.length <= 9, `${mode.id}: short name too long for its plate`);
});

test("in Bomb the clock gets shorter with every hit down to a minimum", () => {
    const bomb = findMode("bomba");
    assert.equal(secondsForQuestion(bomb, 0), 15);
    assert.equal(secondsForQuestion(bomb, 3), 12);
    assert.equal(secondsForQuestion(bomb, 100), bomb.minimumSeconds);
    assert.equal(secondsForQuestion(findMode("clasico"), 5), null);
});

test("Climb raises each hit in a row by 25 % up to ×2, and other modes never climb", () => {
    const climb = findMode("escalada");
    assert.equal(climbFactor(climb, 1), 1);
    assert.equal(climbFactor(climb, 3), 1.5);
    assert.equal(climbFactor(climb, 50), MAX_CLIMB);
    assert.equal(climbFactor(findMode("clasico"), 50), 1);
    // A mode can't push a hit over the database's 2,500 cap (250 × 2 × 5).
    for (const mode of MODES) assert.ok(mode.multiplier * climbFactor(mode, 99) <= 2, `${mode.id}: multiplier too high`);
});

test("50/50 shows two answers and every mode ends somehow", () => {
    assert.equal(findMode("cincuenta").answersShown, 2);
    for (const mode of MODES) {
        const ends = mode.totalQuestions !== null || mode.lives !== null || mode.totalSeconds !== null;
        assert.ok(ends, `${mode.id}: the game would never end`);
    }
});

test("leagues are ordered and depend only on points", () => {
    for (let i = 1; i < LEAGUES.length; i++) assert.ok(LEAGUES[i].minimum > LEAGUES[i - 1].minimum);
    assert.equal(leagueFor(0).id, "bronze");
    assert.equal(leagueFor(LEAGUES[2].minimum).id, LEAGUES[2].id);
    assert.equal(leagueFor(LEAGUES[2].minimum - 1).id, LEAGUES[1].id);
    assert.equal(leagueFor(999999).id, LEAGUES[LEAGUES.length - 1].id);
    const progress = leagueProgress(LEAGUES[1].minimum + 10);
    assert.equal(progress.next?.id, LEAGUES[2].id);
    assert.equal(progress.missing, LEAGUES[2].minimum - LEAGUES[1].minimum - 10);
    assert.equal(leagueProgress(999999).next, null);
});

test("registrar_partida accepts the same modes as the game (Versus goes through challenges)", () => {
    const list = sql.match(/p_modo not in \(([^)]*)\)/)?.[1] ?? "";
    const databaseModes = [...list.matchAll(/'([a-z-]+)'/g)].map((match) => match[1]).sort();
    assert.deepEqual(databaseModes, MODES.map((mode) => mode.id).sort());
});

test("the database gives the same league points as the game", () => {
    const body = sql.slice(sql.indexOf("create or replace function public.responder_reto"));
    assert.match(body, new RegExp(`v_resultado := 'victoria'; v_cambio := ${LEAGUE_POINTS.win};\\s+v_cambio_ret := ${LEAGUE_POINTS.loss};`));
    assert.match(body, new RegExp(`v_resultado := 'empate';\\s+v_cambio := ${LEAGUE_POINTS.draw};`));
    assert.match(body, new RegExp(`v_resultado := 'derrota';\\s+v_cambio := ${LEAGUE_POINTS.loss};`));
});

test("the database accepts the highest score the game can produce (×5 multiplier)", () => {
    assert.match(sql, /p_puntos > p_aciertos \* 2500/);
    assert.doesNotMatch(sql, /p_aciertos \* 500/);
});

test("friend codes are generated by the database and never equal the username or name", () => {
    assert.match(sql, /create function public\.generar_codigo_amigo\(p_usuario text default null, p_nombre text default null\)/);
    assert.match(sql, /position\(v_codigo in v_propio\) = 0/);
    assert.match(sql, /generar_codigo_amigo\(new\.usuario, new\.nombre\)/);
    assert.match(sql, /grant execute on function public\.asegurar_codigo_amigo\(\) to authenticated;/);
    assert.doesNotMatch(sql, /grant execute on function public\.asegurar_codigo_amigo\(\) to anon/);
});

test("ranking returns games, hits and questions of every player", () => {
    const body = sql.slice(sql.indexOf("create function public.ranking("));
    const returns = body.slice(0, body.indexOf("language sql"));
    for (const column of ["partidas", "aciertos", "preguntas"]) assert.match(returns, new RegExp(`\\n\\s+${column}\\s+integer,`), column);
    assert.match(body, /o\.partidas, o\.aciertos, o\.preguntas,/);
});

test("challenges can only be read and written through functions", () => {
    assert.match(sql, /alter table public\.retos\s+enable row level security;/);
    assert.match(sql, /revoke all on public\.retos from anon, authenticated;/);
    assert.doesNotMatch(sql, /create policy [^;]* on public\.retos/);
    for (const name of ["crear_reto", "mis_retos", "preguntas_reto", "responder_reto", "rechazar_reto"]) {
        const prefix = `grant execute on function public.${name}(`;
        const grants = sql.split("\n").filter((line) => line.startsWith(prefix));
        assert.ok(grants.some((line) => line.endsWith(") to authenticated;")), `${name} has no permission`);
        assert.ok(!grants.some((line) => line.includes("anon")), `${name} is open to anonymous users`);
    }
});
