/**
 * session.ts
 * The player's Supabase account: sign up and log in with username and
 * password (no e-mail), log out, change the password, profile photo,
 * accumulated points and each mode's records.
 *
 * Supabase requires an e-mail, so an internal "<username>@quizmania.app"
 * is used (see config/rules.ts). "Confirm email" must be off in Supabase.
 *
 * Every session or profile change fires SESSION_CHANGED on document so the
 * interface repaints.
 */

import type { ModeId } from "../config/modes";
import { internalEmail, isValidUsername, MIN_PASSWORD_LENGTH, normalizeUsername } from "../config/rules";
import { AVATAR_BUCKET, hasSavedSession, loadSupabase, SUPABASE_CONFIGURED, SUPABASE_URL } from "./supabase";

/** Event fired on document when logging in, out or changing the profile. */
export const SESSION_CHANGED = "quizmania:session";

/** Side of the uploaded profile photo (px). */
const AVATAR_SIZE = 256;
/** Largest image the player may choose (before it's reduced). */
const MAX_IMAGE_SIZE = 15 * 1024 * 1024;
/** Longest display name (same as the database). */
export const MAX_NAME_LENGTH = 24;

/** Data of the logged-in player. */
export interface Profile {
    id: string;
    username: string;
    /** Display name chosen by the player (null = the username is shown). */
    name: string | null;
    /**
     * Friend code: 6 characters generated by the database, different from
     * the username and the name. null only while the database lacks the
     * column (supabase/schema.sql hasn't been run yet).
     */
    code: string | null;
    avatarVersion: number | null;
    totalPoints: number;
    games: number;
    hits: number;
    questions: number;
    /** Versus league points (never expire). */
    leaguePoints: number;
    wins: number;
    draws: number;
    losses: number;
}

/** Result of saving a game on the server. */
export interface OnlineGameResult {
    previous: number;
    best: number;
    newRecord: boolean;
    totalPoints: number;
}

/** Account error with a short code the interface translates. */
export class AccountError extends Error {
    /** @param code Short error code (see accountErrorMessage in account-ui.ts). */
    constructor(readonly code: string) {
        super(code);
    }
}

let profile: Profile | null = null;
/** The player's records on the server, per mode. */
let onlineRecords = new Map<string, { best: number; games: number }>();
/** true when the database is missing the latest schema (friend codes, Versus…). */
let databaseOutdated = false;

/**
 * Upper-cases the first letter ("jondals" → "Jondals").
 * @param text Text.
 */
export function capitalize(text: string): string {
    const [first = "", ...rest] = [...text];
    return first.toLocaleUpperCase() + rest.join("");
}

/**
 * Name shown for a player: their display name or, if none, their username;
 * always starting with a capital letter.
 * @param player Username and name.
 */
export function displayName(player: { username: string; name?: string | null }): string {
    return capitalize(player.name?.trim() || player.username);
}

/** Whether the game has Supabase configured. */
export function isOnline(): boolean {
    return SUPABASE_CONFIGURED;
}

/** Logged-in player's profile, or null when playing as a guest. */
export function getProfile(): Profile | null {
    return profile;
}

/** Whether the database still lacks the latest schema.sql. */
export function isDatabaseOutdated(): boolean {
    return databaseOutdated;
}

/**
 * Server record of a mode (only with a session).
 * @param mode Mode id or "total".
 */
export function getOnlineRecord(mode: ModeId | "total"): { best: number; games: number } {
    return onlineRecords.get(mode) ?? { best: 0, games: 0 };
}

/**
 * Public URL of a player's photo.
 * @param id Player id.
 * @param version Photo version (null = none).
 */
export function avatarUrl(id: string, version: number | null): string | null {
    return version === null || !SUPABASE_URL ? null : `${SUPABASE_URL}/storage/v1/object/public/${AVATAR_BUCKET}/${id}/avatar?v=${version}`;
}

/** Tells the interface the session or profile changed. */
function notify(): void {
    document.dispatchEvent(new CustomEvent(SESSION_CHANGED));
}

/** Returns the client (loading Supabase the first time) or throws when it isn't configured. */
async function client() {
    if (!SUPABASE_CONFIGURED) throw new AccountError("no-server");
    return loadSupabase();
}

/**
 * Turns a Supabase error into an AccountError with a known code.
 * @param error Error received.
 */
function translateError(error: { message?: string; code?: string } | null): AccountError {
    const message = (error?.message ?? "").toLowerCase();
    const code = error?.code ?? "";
    if (message.includes("invalid login credentials") || code === "invalid_credentials") return new AccountError("credentials");
    if (message.includes("already registered") || code === "user_already_exists") return new AccountError("username-taken");
    if (message.includes("password") && (message.includes("short") || message.includes("weak") || message.includes("least"))) {
        return new AccountError("short-password");
    }
    if (message.includes("email not confirmed")) return new AccountError("confirm-email");
    if (code === "over_email_send_rate_limit" || message.includes("email rate limit") || message.includes("sending confirmation")) {
        // Supabase tries to send the confirmation e-mail: "Confirm email" must be turned off.
        return new AccountError("confirm-email");
    }
    if (message.includes("rate limit") || code === "over_request_rate_limit") return new AccountError("too-many-attempts");
    if (message.includes("failed to fetch") || message.includes("network")) return new AccountError("offline");
    if (code === "PGRST202" || code === "42703" || code === "42883") return new AccountError("outdated-database");
    // Database functions raise short codes such as "usuario-no-existe".
    const ownCode = message.match(/^[a-z-]+$/)?.[0];
    return new AccountError(ownCode ?? "unknown");
}

/**
 * Returns the player's friend code. If the profile has none yet (it was
 * created before codes existed) the database creates it on the spot. A code
 * is never invented here: one not stored in the database couldn't be used
 * to add you.
 * @param db Supabase client.
 * @param code Code that came with the profile, if any.
 * @returns The code, or null if the database has no codes yet.
 */
async function ensureFriendCode(db: Awaited<ReturnType<typeof client>>, code: string | null): Promise<string | null> {
    if (code) return code;
    const { data, error } = await db.rpc("asegurar_codigo_amigo");
    if (error || typeof data !== "string") {
        console.warn("QuizMania: the database has no friend codes. Run supabase/schema.sql.", error?.message);
        return null;
    }
    return data;
}

/**
 * Downloads the profile and records of the logged-in player.
 * @param id Player id.
 */
async function loadProfile(id: string): Promise<void> {
    const db = await client();
    const [profileResponse, recordsResponse] = await Promise.all([
        // "*" and not a column list: it keeps working even if a new column is missing.
        db.from("perfiles").select("*").eq("id", id).single(),
        db.from("records").select("modo, mejor, partidas").eq("usuario_id", id),
    ]);
    if (profileResponse.error || !profileResponse.data) throw translateError(profileResponse.error);
    const row = profileResponse.data;
    databaseOutdated = !("codigo" in row) || !("puntos_liga" in row);
    profile = {
        id: row.id,
        username: row.usuario,
        name: row.nombre ?? null,
        code: await ensureFriendCode(db, row.codigo ?? null),
        avatarVersion: row.avatar_version,
        totalPoints: Number(row.puntos_totales),
        games: row.partidas,
        hits: row.aciertos,
        questions: row.preguntas,
        leaguePoints: Number(row.puntos_liga ?? 0),
        wins: Number(row.victorias ?? 0),
        draws: Number(row.empates ?? 0),
        losses: Number(row.derrotas ?? 0),
    };
    onlineRecords = new Map((recordsResponse.data ?? []).map((record) => [record.modo, { best: record.mejor, games: record.partidas }]));
    notify();
}

/** Restores the session saved in the browser (if any). */
export async function restoreSession(): Promise<void> {
    // Without a saved session there's nothing to restore: Supabase isn't even loaded.
    if (!SUPABASE_CONFIGURED || !hasSavedSession()) return;
    const supabase = await loadSupabase();
    const { data } = await supabase.auth.getSession();
    if (!data.session) return;
    try {
        await loadProfile(data.session.user.id);
    } catch {
        // Expired session or deleted profile: play as a guest.
        await supabase.auth.signOut().catch(() => {});
        profile = null;
        notify();
    }
}

/**
 * Checks username and password before sending them.
 * @returns The normalised username.
 */
function validateCredentials(typedUsername: string, password: string): string {
    const username = normalizeUsername(typedUsername);
    if (!isValidUsername(username)) throw new AccountError("invalid-username");
    if (password.length < MIN_PASSWORD_LENGTH) throw new AccountError("short-password");
    return username;
}

/**
 * Logs in with username and password.
 * @param typedUsername Username as typed.
 * @param password Password.
 */
export async function logIn(typedUsername: string, password: string): Promise<void> {
    const username = validateCredentials(typedUsername, password);
    const { data, error } = await (await client()).auth.signInWithPassword({ email: internalEmail(username), password });
    if (error || !data.user) throw translateError(error);
    await loadProfile(data.user.id);
}

/**
 * Creates a new account and logs in with it.
 * @param typedUsername Chosen username.
 * @param password Password.
 */
export async function signUp(typedUsername: string, password: string): Promise<void> {
    const username = validateCredentials(typedUsername, password);
    const db = await client();
    const available = await db.rpc("usuario_disponible", { p_usuario: username });
    if (available.error) throw translateError(available.error);
    if (available.data === false) throw new AccountError("username-taken");

    const { data, error } = await db.auth.signUp({ email: internalEmail(username), password, options: { data: { usuario: username } } });
    if (error) throw translateError(error);
    if (data.session && data.user) {
        await loadProfile(data.user.id);
        return;
    }
    // With "Confirm email" on Supabase returns no session, although the
    // database confirms the account itself (confirmar_usuario trigger): log in.
    await logIn(username, password);
}

/**
 * Changes the display name (empty = show the username again).
 * @param name New name.
 */
export async function changeName(name: string): Promise<void> {
    if (!profile) throw new AccountError("not-logged-in");
    const clean = name.replace(/[\u0000-\u001f<>]/g, "").trim();
    if ([...clean].length > MAX_NAME_LENGTH) throw new AccountError("nombre-no-valido");
    const { data, error } = await (await client()).rpc("cambiar_nombre", { p_nombre: clean });
    if (error) throw translateError(error);
    profile = { ...profile, name: (data as string | null) ?? null };
    notify();
}

/** Logs out (the game continues as a guest). */
export async function logOut(): Promise<void> {
    await (await client()).auth.signOut();
    profile = null;
    onlineRecords = new Map();
    notify();
}

/**
 * Changes the password, checking the current one first.
 * @param current Current password.
 * @param next New password.
 */
export async function changePassword(current: string, next: string): Promise<void> {
    if (!profile) throw new AccountError("not-logged-in");
    if (next.length < MIN_PASSWORD_LENGTH) throw new AccountError("short-password");
    const db = await client();
    const check = await db.auth.signInWithPassword({ email: internalEmail(profile.username), password: current });
    if (check.error) throw new AccountError("current-password");
    const { error } = await db.auth.updateUser({ password: next });
    if (error) throw translateError(error);
}

/**
 * Crops the image to a centred square and reduces it to AVATAR_SIZE px.
 * @param file Image chosen by the player.
 * @returns The image as WebP (or PNG if the browser can't make WebP).
 */
async function prepareImage(file: File): Promise<Blob> {
    if (!file.type.startsWith("image/")) throw new AccountError("invalid-image");
    if (file.size > MAX_IMAGE_SIZE) throw new AccountError("image-too-big");
    let image: ImageBitmap;
    try {
        image = await createImageBitmap(file);
    } catch {
        throw new AccountError("invalid-image");
    }
    const side = Math.min(image.width, image.height);
    const canvas = document.createElement("canvas");
    canvas.width = AVATAR_SIZE;
    canvas.height = AVATAR_SIZE;
    const brush = canvas.getContext("2d");
    if (!brush) throw new AccountError("invalid-image");
    brush.imageSmoothingQuality = "high";
    brush.drawImage(image, (image.width - side) / 2, (image.height - side) / 2, side, side, 0, 0, AVATAR_SIZE, AVATAR_SIZE);
    image.close();
    return new Promise((resolve, reject) => {
        canvas.toBlob((blob) => (blob ? resolve(blob) : reject(new AccountError("invalid-image"))), "image/webp", 0.85);
    });
}

/**
 * Uploads a new profile photo (cropped and reduced).
 * @param file Chosen image.
 */
export async function uploadAvatar(file: File): Promise<void> {
    if (!profile) throw new AccountError("not-logged-in");
    const db = await client();
    const image = await prepareImage(file);
    const { error } = await db.storage.from(AVATAR_BUCKET).upload(`${profile.id}/avatar`, image, { upsert: true, contentType: image.type, cacheControl: "31536000" });
    if (error) throw translateError(error);
    const version = await db.rpc("avatar_actualizado");
    if (version.error) throw translateError(version.error);
    profile = { ...profile, avatarVersion: version.data as number };
    notify();
}

/** Deletes the profile photo. */
export async function removeAvatar(): Promise<void> {
    if (!profile) throw new AccountError("not-logged-in");
    const db = await client();
    await db.storage.from(AVATAR_BUCKET).remove([`${profile.id}/avatar`]);
    const { error } = await db.rpc("quitar_avatar");
    if (error) throw translateError(error);
    profile = { ...profile, avatarVersion: null };
    notify();
}

/** Data of a finished game. */
export interface GameData {
    mode: ModeId;
    topic: string;
    points: number;
    hits: number;
    total: number;
}

/**
 * Saves a game on the server: adds its points to the total and updates the record.
 * @param game Game data.
 */
export async function saveGameOnline(game: GameData): Promise<OnlineGameResult> {
    if (!profile) throw new AccountError("not-logged-in");
    const { data, error } = await (await client()).rpc("registrar_partida", {
        p_modo: game.mode,
        p_tema: game.topic,
        p_puntos: game.points,
        p_aciertos: game.hits,
        p_total: game.total,
    });
    if (error) throw translateError(error);
    const result = data as { anterior: number; mejor: number; nuevo_record: boolean; puntos_totales: number };
    const previous = onlineRecords.get(game.mode);
    onlineRecords.set(game.mode, { best: result.mejor, games: (previous?.games ?? 0) + 1 });
    profile = {
        ...profile,
        totalPoints: Number(result.puntos_totales),
        games: profile.games + 1,
        hits: profile.hits + game.hits,
        questions: profile.questions + game.total,
    };
    notify();
    return { previous: result.anterior, best: result.mejor, newRecord: result.nuevo_record, totalPoints: Number(result.puntos_totales) };
}

/**
 * Stores the result of a Versus challenge in the profile (the database computed it).
 * @param league New league points and score.
 */
export function updateLeague(league: { leaguePoints: number; wins: number; draws: number; losses: number }): void {
    if (!profile) return;
    profile = { ...profile, ...league };
    notify();
}

/**
 * Deletes the player's account forever: the photo (through the Storage
 * API) and then, in the database, the user, profile, records, friendships
 * and challenges.
 */
export async function deleteAccount(): Promise<void> {
    if (!profile) throw new AccountError("not-logged-in");
    const db = await client();
    // Without a photo, the removal simply finds nothing.
    await db.storage.from(AVATAR_BUCKET).remove([`${profile.id}/avatar`]);
    const { error } = await db.rpc("borrar_mi_cuenta");
    if (error) throw translateError(error);
    // The session is no longer valid: close it only in this browser.
    await db.auth.signOut({ scope: "local" }).catch(() => {});
    profile = null;
    onlineRecords = new Map();
    notify();
}
